### ISSUE TITLE
TPT simulation ~2-3x slower on ubuntu 20.04 compared to windows and ubuntu 18.04

### ISSUE THREAD

**Issue by wolfy1339** [MrCarroll/the-powder-toy-snap#1]
I able to get ~100fps on windows and remember how I was getting ~120fps on ubuntu 18.04 in my build when fpscap set to 2
but on ubuntu 20.04 I can get no more then 60fps and 40fps in average with the same save.
Where possibly a problem can be?

_Originally posted by @jebbyk in https://github.com/The-Powder-Toy/The-Powder-Toy/issues/756_

**Comment by wolfy1339** [comment]
looks like it is debug version presented in ubuntu software

_Originally posted by @jebbyk in https://github.com/The-Powder-Toy/The-Powder-Toy/issues/756#issuecomment-748951002_

**Comment by JGCarroll** [comment]
Thanks for the info, I'll take a look at it in the next few hours

**Comment by wolfy1339** [comment]
It seems you aren't passing the `--release` flag to scons in https://github.com/MrCarroll/the-powder-toy-snap/blob/cc8c516febcd652a4ee2eaaceab74ce92fd9ca25/snap/snapcraft.yaml#L24-L25
That should greatly improve the simulation speed

**Comment by JGCarroll** [comment]
Yeah, that's basically it. The second sentence of https://powdertoy.co.uk/Wiki/W/Scons_command_line_flags.html said that --release and --sse and --sse2 were all automatic, but this clearly isn't the case.

I've tested the current version of the snap store against a build with those explicitly passed and the performance difference is incredibly obvious. At the moment I'm working on pushing a build to the Snap repo and I'll post back when its available. (It shouldn't be more than 20 minutes or so)

https://github.com/MrCarroll/the-powder-toy-snap/commit/d22cc2d837412d65f19bbd5432e3e6ee752202c2

**Comment by wolfy1339** [comment]
Fixes The-Powder-Toy/The-Powder-Toy#756

**Comment by JGCarroll** [comment]
Revision 15 is now available on the Snap Store on the Stable channel, if you want to try it out you can run `sudo snap refresh` to update manually and existing installs will automatically update in the next few days.

(And I'll update the linked issue with this info too)
